# docker-compose.yml
version: "3.8"
name: e-coomerce
services:
  home:
    build: ./home
    ports:
      - "80:80"

  user:
    build: ./user
    ports:
      - "81:80"

  # proxy:
  #   image: nginx:alpine
  #   ports:
  #     - 80:80
  #     - 443:443
  #   volumes:
  #     - ./nginx/conf/nginx.conf:/etc/nginx/nginx.conf
  #     - ./nginx/certs:/etc/nginx/certs
  #   depends_on:
  #     - frontend
